flask_app/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, Length
from flask_wtf.file import FileField, FileAllowed


class ActionForm(FlaskForm):
    submit = SubmitField('Action')
    
class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired(), Length(max=25)])
    image = FileField('Image', validators=[FileAllowed(['jpg', 'png', 'jpeg'])])    
    content = TextAreaField('Content', validators=[DataRequired(), Length(max=200)])
    remove_img = SubmitField('Remove')
    submit = SubmitField('Post')

class CommentsForm(FlaskForm):
    content = TextAreaField('Comment', validators=[DataRequired(), Length(max=200)])
    submit = SubmitField('Post')
    
class SearchForm(FlaskForm):
    search = StringField('Search', validators=[Length(min=3)])
    submit = SubmitField('Search')

flask_app/posts/routes.py
from flask import render_template, flash, redirect, url_for, request, abort, Blueprint, current_app
from flask_login import current_user, login_required
from flask_app import db
from flask_app.models import User, Posts, Comments
from flask_app.posts.utils import save_post_pic
import os
from flask_app.posts.forms import PostForm, CommentsForm, ActionForm, SearchForm


posts = Blueprint('posts', __name__)

@posts.route('/post/new', methods=['POST', 'GET'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        if form.image.data:
            filename = save_post_pic(form.image.data)
        else:
            filename = None
        post = Posts(title=form.title.data, content=form.content.data, post_image=filename, user_id=current_user.id)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('new_post.html', title='New Post', form=form, user=current_user, header='New Post', post=None)

@posts.route("/post/<int:post_id>", methods=['POST', 'GET'])
@login_required
def post(post_id):
    post = Posts.query.get_or_404(post_id)
    likes = len(post.likes)
    form = CommentsForm()
    if form.validate_on_submit():
        comment = Comments(content=form.content.data, user_id=current_user.id, post_id=post.id)
        db.session.add(comment)
        db.session.commit()
        flash('Comment successfully created!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
        
    return render_template('post.html', title=post.title, post=post, user=current_user, form=form, likes=likes)

@posts.route('/post/<int:post_id>/update', methods=['POST', 'GET'])
@login_required
def update_post(post_id):
    form = PostForm()    
    post = Posts.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    if request.method == 'POST':
        if form.validate_on_submit():
            post.title = form.title.data
            print(form.title.data)
            post.content = form.content.data
            print(form.content.data)
            if form.image.data:
                filename = save_post_pic(form.image.data)
                if post.post_image:
                    os.remove(os.path.join(current_app.root_path, 'static/post_pics', post.post_image))
                post.post_image = filename         
            db.session.commit()
            flash('Your post has been updated!', 'success')
            
            return redirect(url_for('posts.post', post_id=post.id))
    
    elif request.method == 'GET':      
        form.title.data = post.title
        form.content.data = post.content

    return render_template('new_post.html', title='Update Post', form=form, user=current_user, header='Update Post', post=post)

@posts.route('/post/<int:post_id>/update/delete_img', methods=['POST', 'GET'])
@login_required
def delete_img(post_id):
    post = Posts.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    picture_path = os.path.join(current_app.root_path, 'static/post_pics', post.post_image)
    os.remove(picture_path)
    post.post_image = None
    db.session.commit()
    
    return redirect(url_for('posts.update_post', post_id=post_id))

@posts.route('/post/<int:post_id>/delete', methods=['Post'])
def delete_post(post_id):
    post = Posts.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    if post.post_image:
        picture_path = os.path.join(current_app.root_path, 'static/post_pics', post.post_image)
        os.remove(picture_path)
    for i in post.comments:
        db.session.delete(i)
    
    db.session.delete(post)
    db.session.commit()
    flash("Post successfully deleted!", "success")
    
    return redirect(url_for('main.home'))

@posts.route('/post/<int:post_id>/comment/<int:comment_id>/delete')
def delete_comment(post_id, comment_id):
    comment = Comments.query.get_or_404(comment_id)
    if comment.author != current_user:
        abort(403)
    db.session.delete(comment)
    db.session.commit()
    flash('Comment successfully deleted!', 'success')
    
    return redirect(url_for('posts.post', post_id=post_id))

@posts.route("/post/<int:post_id>/like", methods=['POST'])
@login_required
def like(post_id):
    form = ActionForm()
    if form.validate_on_submit():
        post = Posts.query.get_or_404(post_id)
        current_user.like_post(post)
        db.session.commit()
        
        return redirect(url_for('posts.post', post_id=post_id))
    else:
        return redirect(url_for('main.home'))

@posts.route("/post/<int:post_id>/unlike", methods=['POST'])
@login_required
def unlike(post_id):
    form = ActionForm()
    if form.validate_on_submit():
        post = Posts.query.get_or_404(post_id)
        current_user.unlike_post(post)
        db.session.commit()

        return redirect(url_for('posts.post', post_id=post_id))
    else:
        return redirect(url_for('main.home'))

@posts.route("/posts", methods=['POST', 'GET'])
@login_required
def random_posts():
    page = request.args.get('page', 1, type=int)
    random_posts = Posts.query.paginate(page=page, per_page=8)
    form = SearchForm()
    if form.validate_on_submit():        
        return redirect(url_for('main.search', searched=form.search.data, type=1))
    
    return render_template('content.html', heading='Posts', type='post', data=random_posts, form=form)

flask_app/users/routes.py
from flask_app.users.utils import UserAuth, UserSignUp, save_picture, send_email_reset
import os
from flask_app.models import User
from flask import current_app, render_template, flash, redirect, url_for, request, abort, Blueprint
from flask_app.users.forms import (SignupForm, LoginForm, EditAccountForm,
                              ActionForm, RequestResetForm, 
                             ResetPasswordForm, SearchForm)
from flask_app import db, bcrypt
from flask_login import login_user, current_user, logout_user, login_required
users = Blueprint('users', __name__)

@users.route('/people', methods=['POST', 'GET'])
@login_required
def people():
    page = request.args.get('page', 1, type=int)
    users = current_user.followed.paginate(page=page, per_page=8)
    
    form = SearchForm()
    if form.validate_on_submit():
        return redirect(url_for('main.search', searched=form.search.data, type=0))
    return render_template('content.html', type='users', data=users, form=form, title='People', all=True, heading='Followed Users', none_message="No users followed")

@users.route('/login', methods=['POST', 'GET'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    else: 
        form = LoginForm()
        if form.validate_on_submit():
            if UserAuth(form.email.data, form.password.data):
                login_user(User.query.filter_by(email=form.email.data).first(), remember=form.remember.data)
                next_page = request.args.get('next')
                print(request.args)
                flash('Your have successfully signed in!', category='success')
                
                return redirect(next_page) if next_page else redirect(url_for('main.home'))
            else:
                flash('Login failed! Please check your credentials!', category='danger')
        
        return render_template('login.html', title="Login", form=form)

@users.route('/signup', methods=['POST', 'GET'])
def signup():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    else:    
        form = SignupForm()
        if form.validate_on_submit():
            password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
            UserSignUp(form.username.data, form.email.data, password)
            flash("Account created successfully!", "success")        
            return redirect(url_for('users.login'))
        
        return render_template('signup.html', title="Sign Up", form=form)

@users.route('/logout')
def logout():
    logout_user()
    
    return redirect(url_for('main.home'))

@users.route('/account', methods=['POST', 'GET'])
@login_required
def account():
    if not os.path.exists(os.path.join(current_app.root_path, 'static/profile_pics', current_user.profile_image)):
        current_user.profile_image = 'default.jpg'
    form = EditAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            if current_user.profile_image != 'default.jpg':
                os.remove(os.path.join(current_app.root_path, 'static/profile_pics', current_user.profile_image))
            current_user.profile_image = picture_file

        current_user.username = form.username.data
        current_user.email = form.email.data
        current_user.bio = form.bio.data
        db.session.commit()
        flash('Account changes have been applied.', category='success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
        form.bio.data = current_user.bio
        
    return render_template('account.html', current_user=current_user, user=current_user, form=form, num_of_posts=len(current_user.posts), title=current_user.username)

@users.route("/user/<int:user_id>")
def user(user_id):
    user = User.query.get_or_404(user_id)
    if user == current_user:
        return redirect(url_for('users.account'))
    
    form = ActionForm()
    
    return render_template('account.html', title=user.username, current_user=current_user, user=user, image_file=user.profile_image, num_of_posts=len(user.posts), form=form)

@users.route("/user/<string:username>/followers", methods=['POST', 'GET'])
@login_required
def followers(username):
    user = User.query.filter_by(username=username).first()
    
    if not user:
        abort(404)
    else:
        page = request.args.get('page', 1, type=int)
        followers = user.followers.paginate(page=page, per_page=20)         
        return render_template('content.html', form=None, data=followers, type='users', title='Followers', all=False, heading="Followers", none_message="This user has no followers")

@users.route("/user/<string:username>/followed", methods=['POST', 'GET'])
@login_required
def followed(username):
    user = User.query.filter_by(username=username).first()
    
    if not user:
        abort(404)
    else:
        page = request.args.get('page', 1, type=int)
        followers = user.followed.paginate(page=page, per_page=20)
        return render_template('content.html', form=None, data=followers, type='users', title='Followers', all=False, heading="Followed", none_message="This user hasn't followed anyone")
    
@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_email_reset(user)
        flash('An email to reset your password has been sent.', 'info')
        return redirect(url_for('users.login'))
        
    return render_template('request.html', title='Reset Password', form=form)

@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    
    if not user:
        flash('Token is invalid or expired!', 'warning')
        return redirect(url_for('users.reset_request'))
    
    form = ResetPasswordForm()
    if form.validate_on_submit():
        password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = password
        db.session.commit()
        flash("Your password has been updated!", "success")        
        
        return redirect(url_for('users.login'))
        
    return render_template('reset.html', title='Reset Password', form=form)

@users.route('/follow/<user_username>', methods=['POST', 'GET'])
@login_required
def follow(user_username):
    form = ActionForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=user_username).first()
        if user == None:
            flash(f"User {user_username} doesn't exist.", 'info')
            return redirect(url_for('main.home'))
        if user == current_user:
            flash('You cannot follow yourself!', 'danger')
            return redirect(url_for('users.account'))
        current_user.follow(user)
        db.session.commit()
        flash(f'You are now following {user.username}.', 'info')
        return redirect(url_for('users.user', user_id=user.id))
    else:
        return redirect(url_for('main.home'))


@users.route('/unfollow/<user_username>', methods=['POST', 'GET'])
@login_required
def unfollow(user_username):
    form = ActionForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=user_username).first()
        if user == None:
            flash(f"User {user_username} doesn't exist.", 'info')
            return redirect(url_for('main.home'))
        if user == current_user:
            flash('You cannot unfollow yourself!', 'danger')
            return redirect(url_for('users.account'))
        current_user.unfollow(user)
        db.session.commit()
        flash(f'You have unfollowed user {user.username}.', 'info')
        
        return redirect(url_for('users.user', user_id=user.id))
    else:
        return redirect(url_for('main.home'))
    
@users.route('/<user_id>/delete_user/', methods=['POST', 'GET'])
@login_required
def delete_user(user_id):
    user = User.query.get_or_404(user_id)
    
    if user.profile_image != 'default.jpg':
        picture_path = os.path.join(current_app.root_path, 'static/profile_pics', user.profile_image)
        os.remove(picture_path)
    
    for i in user.liked:
        db.session.delete(i)
    for i in user.comments:
        db.session.delete(i)
    for i in user.posts:
        if i.post_image:
            image_path = os.path.join(current_app.root_path, 'static/post_pics', i.post_image)
            for j in i.comments:
                db.session.delete(j)
            os.remove(image_path)
        db.session.delete(i)
    
    db.session.delete(user)
    db.session.commit()
    logout()
    
    return redirect(url_for('users.login'))

flask_app/templates/account.html
{% extends "layout.html" %}

{% block body %}
    <div class="container d-flex justify-content-center">
        <div class="card p-3 w-50 border-0">
            <div class="d-flex align-items-center">
                <div class="image p-3"> 
                    <img src="{{ url_for('static', filename='profile_pics/' + user.profile_image) }}" class="rounded-circle" width="155" height="155" alt="pfp">
                    
                </div>
                <div class="ml-3 w-100">
                    <h4 class="mb-0 mt-0">{{ user.username }}</h4>
                    <h6 class="mt-2 mb-1">Bio</h6>
                    {% if user.bio %}
                        <p class="border border-light rounded p-2" style="max-width: 43ch; white-space: pre-wrap;">{{ user.bio }}</p>
                    {% else %}
                        <p class="border border-light rounded p-2 text-muted" style="max-width: 43ch;">No bio entered</p>
                    {% endif %}
                    <div class="p-2 mt-2 bg-primary d-flex justify-content-around rounded text-white stats w-100">
                        <div class=" flex-column"> 
                            <span class="fs-6">Posts:</span> 
                            <span class="number1">{{num_of_posts}}</span> 
                        </div>
                        <div class="flex-column"> 
                            <span class="fs-6"><a class="text-white text-decoration-none" href="{{ url_for('users.followers', username=user.username) }}">Followers:</a></span> 
                            <span class="number2">{{ user.followers.count() }}</span> 
                        </div>
                        <div class="flex-column"> 
                            <span class="fs-6"><a class="text-white text-decoration-none" href="{{ url_for('users.followed', username=user.username) }}">Followed: </a></span> 
                            <span class="number2">{{ user.followed.count() }}</span> 
                        </div>
                    </div>
                    {% if not user == current_user %}
                        <div class="button mt-2 d-flex flex-row align-items-center">
                            {% if not current_user.is_following(user) %}
                                <form class="w-100" action="{{ url_for('users.follow', user_username=user.username) }}" method="POST">
                                    {{ form.hidden_tag() }}
                                    {{ form.submit(value='Follow', class='btn btn-outline-primary w-100 m-1 btn-sm ') }}
                                </form>
                            {% else %}
                                <form class="w-100" action="{{ url_for('users.unfollow', user_username=user.username) }}" method="POST">
                                    {{ form.hidden_tag() }}
                                    {{ form.submit(value='Unfollow', class='btn btn-outline-danger w-100 m-1 btn-sm ') }}
                                </form>
                            {% endif %}
                        </div>
                    {% else %}
                        <a class="btn btn-primary w-100 mt-2" data-toggle="collapse" href="#edit-info" role="button" aria-expanded="false" aria-controls="collapseExample">
                            Edit Account Details
                        </a>
                    {% endif %}
                </div>
            </div>
            
            {% if user == current_user %}
                <div class="collapse" id="edit-info">
                    <form method="POST" class="d-flex justify-content-center mt-5" action="" enctype="multipart/form-data">
                        <div class="card">
                            <h4 class="card-header">Edit Account Details</h5>
                            <div class="card-body">
                            {{ form.hidden_tag() }}
                            <div class="form-floating mb-3">
                                {% if form.username.errors %}
                                    {{ form.username(class="form-control is-invalid", id="floatingInput", placeholder="John Doe") }}
                                    <div class="invalid-feedback">
                                        {% for error in form.username.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                {% else %}
                                    {{ form.username(type="username", class="form-control", id="floatingInput", placeholder="John Doe") }}
                                {% endif %}
                                {{ form.username.label(for="floatingInput") }}
                            </div>  
                            <div class="form-floating mb-3">
                                {% if form.email.errors %}
                                    {{ form.email(class="form-control is-invalid", id="floatingInput", placeholder="John Doe") }}
                                    <div class="invalid-feedback">
                                        {% for error in form.email.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                {% else %}
                                    {{ form.email(class="form-control", id="floatingInput", placeholder="John Doe") }}
                                {% endif %}
                                {{ form.email.label(for="floatingInput") }}
                            </div >
                            <div class="form-floating mb-3">
                                {% if form.bio.errors %}
                                    {{ form.bio(class="form-control is-invalid", id="floatingInput", style="width: 43ch", placeholder="John Doe") }}
                                    <div class="invalid-feedback">
                                        {% for error in form.bio.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                {% else %}
                                    {{ form.bio(class="form-control", id="floatingInput", style="width: 43ch", placeholder="John Doe") }}
                                {% endif %}
                                {{ form.bio.label(for="floatingInput") }}
                            </div>
                            <div>
                                {{ form.picture.label(class="form-label") }}
                                {{ form.picture(class="form-control", type="file", id="formFile") }}
                                {% if form.picture.errors %}
                                    {% for error in form.picture.errors %}
                                        <span class="text-danger">{{ error }}</span><br>
                                    {% endfor %}
                                {% endif %}
                            </div>
                            <div class="mt-3">
                                {{ form.submit(class="btn btn-primary col") }}
                                <button type="button" class="col btn btn-danger" data-toggle="modal" data-target="#deleteModal">Delete Account</button>

                            </div>  
                            </div>
                        </div>
                    </form>
                </div>
                
            {% endif %}
        </div>
    </div>
    <div class="d-flex justify-content-center">
        <div class="card p-3 w-75 mt-3 d-flex justify-content-center">
            <h2 class="d-flex justify-content-center">Posts</h2>
                {% for post in user.posts[::-1] %}
                    <div class="d-flex justify-content-center">
                        <div class="card mt-3" style="width: 45rem;"> 
                            {% if post.post_image %}
                                <img src="{{ url_for('static', filename='post_pics/' + post.post_image) }}" class="card-img-top" alt="...">
                            {% endif %}
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-1 ml-lg-1">
                                        <img class="rounded-circle" style="height: 55px; width: 55px;" src="{{ url_for('static', filename='profile_pics/' + post.author.profile_image) }}" alt="pfp">
                                    </div>
                                    <div class="col-9 m-2">
                                        <h6 class="card-subtitle m-2 text-muted">
                                            <p class="mr-3">{{ post.author.username }}</p>
                                            <small class="text-muted">{{ post.date_posted.strftime('%Y/%m/%d') }}</small>
                                        </h6>
                                        <h3 class="card-title"><a href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h3>
                                        <div class="border border-secondary rounded p-2">
                                            <p class="card-text "><p class="card-text">{{ post.content }}</p></p> 
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>  
                    </div>    
            {% endfor %}
        </div>
    </div>
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">Are you sure you want to delete your account?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <form method="POST" action="{{ url_for('users.delete_user', user_id=user.id) }}">
                        <input class="btn btn-danger" type="submit" value="Delete">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

flask_app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="icon" type="image/png" href="{{ url_for('static', filename='favicon.png')}}">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    
    {% if title %}
        <title> {{ title }} </title>
    {% else %}
        <title>Flask App</title>
    {% endif %}
</head>
<body>
    <header class="site-header">

        <nav class="navbar navbar-expand-md navbar-light bg-light position-sticky">
            <div class="container">
                <a class="navbar-brand mr-4" href="{{ url_for('main.home') }}">Twistagram</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('main.home') }}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('users.people') }}">People</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('posts.random_posts') }}">Posts</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav d-flex">
                        {% if current_user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('users.account') }}">Account</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('users.login') }}">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('users.signup') }}">Sign Up</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <main role="main" class="container mt-4">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                <div class="alert alert-{{ category }}" role="alert">
                    {{ message }}
                </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
        {% block body %}{% endblock %}
    </main>

</body>
</html>

flask_app/templates/request.html
{% extends "layout.html" %}

{% block body %}
    
    <form method="POST" action="">
        <div class="card">
            <h4 class="card-header">Reset Password</h5>
            <div class="card-body">
                {{ form.hidden_tag() }}
                <div class="form-floating mb-3">
                    {% if form.email.errors %}
                        {{ form.email(class="form-control is-invalid", id="floatingInput", placeholder="name@example.com")}}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control", id="floatingInput", placeholder="name@example.com")}}
                    {% endif %}
                        {{ form.email.label(for="floatingInput") }}
                </div>                
                <div class="mt-3">
                    {{ form.submit(class="btn btn-primary") }}
                </div>
            </div>
        </div>
    </form>
        
{% endblock %}